<?xml version="1.0" encoding="utf-8"?><Database Name="Storage" Class="StorageItemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Storage.mdf;Integrated Security=True" SettingsObjectName="Agile_Assignment.My.MySettings" SettingsPropertyName="StorageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ItemID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ItemPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>